// Constantes de statuts HTTP et codes d'erreurs métiers standardisés
// Respect strict des standards de sécurité et de traçabilité bancaire

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const ERROR_CODES = {
  // Erreurs d'authentification et sécurité
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PIN_BLOCKED: 'PIN_BLOCKED',
  INVALID_PIN: 'INVALID_PIN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',

  // Erreurs OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_COOLDOWN: 'OTP_COOLDOWN',

  // Erreurs Groupes et Membres
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_FULL: 'GROUP_FULL',
  INVALID_GROUP_PASSWORD: 'INVALID_GROUP_PASSWORD',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  CANNOT_REMOVE_ADMIN: 'CANNOT_REMOVE_ADMIN',

  // Erreurs Transactions et Cycles
  TRANSACTION_DUPLICATE: 'TRANSACTION_DUPLICATE',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_PROCESSED: 'TRANSACTION_ALREADY_PROCESSED',
  CYCLE_NOT_FOUND: 'CYCLE_NOT_FOUND',
  TOUR_NOT_FOUND: 'TOUR_NOT_FOUND',
  INELIGIBLE_FOR_TOUR: 'INELIGIBLE_FOR_TOUR',

  // Erreurs Validation et Données
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type HttpStatusCode = typeof HTTP_STATUS[keyof typeof HTTP_STATUS];
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
